var nbastadiumData= [
  {
    "StadiumName": "State Farm Arena",
    "longitude": -84.3985184,
    "latitude": 33.7572935,
    "website": "https://www.nba.com/hawks/",
    "Team": "Atlanta Hawks",
    "Logo": "http://oit2.sps.nyu.edu/~tj986/Markericon/Atlanta%20Hawks.png",
    "Conference": "East",
    "Divisions": "SOUTHEAST",
    "Year": 1999,
    "Picture": "http://oit2.sps.nyu.edu/~tj986/Markericon/Image/Atlanta.jpg",
    "Capacity": "21,000"
  },
  {
    "StadiumName": "TD Garden",
    "longitude": -71.06434,
    "latitude": 42.3662019,
    "website": "https://www.nba.com/celtics/",
    "Team": "Boston Celtics",
    "Logo": "http://oit2.sps.nyu.edu/~tj986/Markericon/Boston%20Celtics.png",
    "Conference": "East",
    "Divisions": "ATLANTIC",
    "Year": 1995,
    "Picture": "http://oit2.sps.nyu.edu/~tj986/Markericon/Image/Boston.jpg",
    "Capacity": "19,580"
  },
  {
    "StadiumName": "Barclays Center",
    "longitude": -73.9776096,
    "latitude": 40.6826505,
    "website": "https://www.nba.com/nets/",
    "Team": "Brooklyn Nets",
    "Logo": "http://oit2.sps.nyu.edu/~tj986/Markericon/Brooklyn%20Nets.png",
    "Conference": "East",
    "Divisions": "ATLANTIC",
    "Year": 2012,
    "Picture": "http://oit2.sps.nyu.edu/~tj986/Markericon/Image/Brooklyn.jpg",
    "Capacity": "19,000"
  },
  {
    "StadiumName": "Spectrum Center",
    "longitude": -80.8414977,
    "latitude": 35.2251853,
    "website": "https://www.nba.com/hornets/",
    "Team": "Charlotte Hornets",
    "Logo": "http://oit2.sps.nyu.edu/~tj986/Markericon/Charlotte%20Hornets.png",
    "Conference": "East",
    "Divisions": "SOUTHEAST",
    "Year": 2005,
    "Picture": "http://oit2.sps.nyu.edu/~tj986/Markericon/Image/Charlotte.jpg",
    "Capacity": "20,200"
  },
  {
    "StadiumName": "United Center",
    "longitude": -87.6763699,
    "latitude": 41.8806948,
    "website": "https://www.nba.com/bulls/",
    "Team": "Chicago Bulls",
    "Logo": "http://oit2.sps.nyu.edu/~tj986/Markericon/Chicago%20Bulls.png",
    "Conference": "East",
    "Divisions": "CENTRAL",
    "Year": 1994,
    "Picture": "http://oit2.sps.nyu.edu/~tj986/Markericon/Image/Chicago.jpg",
    "Capacity": "23,500"
  },
  {
    "StadiumName": "Quicken Loans Arena",
    "longitude": -81.6904069,
    "latitude": 41.4964837,
    "website": "https://www.nba.com/cavaliers/",
    "Team": "Cleveland Cavaliers",
    "Logo": "http://oit2.sps.nyu.edu/~tj986/Markericon/Cleveland%20Cavaliers.png",
    "Conference": "East",
    "Divisions": "CENTRAL",
    "Year": 1994,
    "Picture": "http://oit2.sps.nyu.edu/~tj986/Markericon/Image/Cleveland.jpg",
    "Capacity": "20,562"
  },
  {
    "StadiumName": "American Airlines Center",
    "longitude": -96.8173592,
    "latitude": 32.7848939,
    "website": "https://www.mavs.com/",
    "Team": "Dallas Mavericks",
    "Logo": "http://oit2.sps.nyu.edu/~tj986/Markericon/Dallas%20Mavericks.png",
    "Conference": "West",
    "Divisions": "SOUTHWEST",
    "Year": 2001,
    "Picture": "http://oit2.sps.nyu.edu/~tj986/Markericon/Image/Dallas.jpg",
    "Capacity": "20,000"
  },
  {
    "StadiumName": "Pepsi Center",
    "longitude": -105.009904,
    "latitude": 39.7486641,
    "website": "https://www.nba.com/nuggets/",
    "Team": "Denver Nuggets",
    "Logo": "http://oit2.sps.nyu.edu/~tj986/Markericon/Denver%20Nuggets.png",
    "Conference": "West",
    "Divisions": "NORTHWEST",
    "Year": 1999,
    "Picture": "http://oit2.sps.nyu.edu/~tj986/Markericon/Image/Denver.jpg",
    "Capacity": "18,007"
  },
  {
    "StadiumName": "The Palace of Auburn Hills",
    "longitude": -83.2447494,
    "latitude": 42.698533,
    "website": "https://www.nba.com/pistons/",
    "Team": "Detroit Pistons",
    "Logo": "http://oit2.sps.nyu.edu/~tj986/Markericon/Detroit%20Pistons.png",
    "Conference": "East",
    "Divisions": "CENTRAL",
    "Year": 1988,
    "Picture": "http://oit2.sps.nyu.edu/~tj986/Markericon/Image/Detroit.jpg",
    "Capacity": "24,276"
  },
  {
    "StadiumName": "Chase Center",
    "longitude": -122.3895203,
    "latitude": 37.7679315,
    "website": "https://www.nba.com/warriors/",
    "Team": "Golden State Warriors",
    "Logo": "http://oit2.sps.nyu.edu/~tj986/Markericon/Golden%20State%20Warriors.png",
    "Conference": "West",
    "Divisions": "PACIFIC",
    "Year": 2019,
    "Picture": "http://oit2.sps.nyu.edu/~tj986/Markericon/Image/Golden.jpg",
    "Capacity": "18,604"
  },
  {
    "StadiumName": "Toyota Center",
    "longitude": -95.3642945,
    "latitude": 29.7507604,
    "website": "https://www.nba.com/rockets/",
    "Team": "Houston Rockets",
    "Logo": "http://oit2.sps.nyu.edu/~tj986/Markericon/Houston%20Rockets.png",
    "Conference": "West",
    "Divisions": "SOUTHWEST",
    "Year": 2003,
    "Picture": "http://oit2.sps.nyu.edu/~tj986/Markericon/Image/Houston.jpg",
    "Capacity": "18,300"
  },
  {
    "StadiumName": "Bankers Life Fieldhouse",
    "longitude": -86.1577307,
    "latitude": 39.7640475,
    "website": "https://www.nba.com/pacers/",
    "Team": "Indiana Pacers",
    "Logo": "http://oit2.sps.nyu.edu/~tj986/Markericon/Indiana%20Pacers.png",
    "Conference": "East",
    "Divisions": "CENTRAL",
    "Year": 1999,
    "Picture": "http://oit2.sps.nyu.edu/~tj986/Markericon/Image/Indiana.jpg",
    "Capacity": "20,000"
  },
  {
    "StadiumName": "STAPLES Center",
    "longitude": -118.2694481,
    "latitude": 34.0430219,
    "website": "https://www.nba.com/clippers/",
    "Team": "Los Angeles Clippers",
    "Logo": "http://oit2.sps.nyu.edu/~tj986/Markericon/Los%20Angeles%20Clippers.png",
    "Conference": "West",
    "Divisions": "PACIFIC",
    "Year": 1999,
    "Picture": "http://oit2.sps.nyu.edu/~tj986/Markericon/Image/LAC.jpg",
    "Capacity": "20,000"
  },
  {
    "StadiumName": "STAPLES Center",
    "longitude": -118.2694481,
    "latitude": 34.0430219,
    "website": "https://www.nba.com/lakers/",
    "Team": "Los Angeles Lakers",
    "Logo": "http://oit2.sps.nyu.edu/~tj986/Markericon/Los%20Angeles%20Lakers.png",
    "Conference": "West",
    "Divisions": "PACIFIC",
    "Year": 1999,
    "Picture": "http://oit2.sps.nyu.edu/~tj986/Markericon/Image/LAL.jpg",
    "Capacity": "20,000"
  },
  {
    "StadiumName": "FedExForum",
    "longitude": -90.0527804,
    "latitude": 35.1381462,
    "website": "https://www.nba.com/grizzlies/",
    "Team": "Memphis Grizzlies",
    "Logo": "http://oit2.sps.nyu.edu/~tj986/Markericon/Memphis%20Grizzlies.png",
    "Conference": "West",
    "Divisions": "SOUTHWEST",
    "Year": 2004,
    "Picture": "http://oit2.sps.nyu.edu/~tj986/Markericon/Image/MEM.jpg",
    "Capacity": "18,119"
  },
  {
    "StadiumName": "American Airlines Arena",
    "longitude": -80.189163,
    "latitude": 25.7814062,
    "website": "https://www.nba.com/heat/",
    "Team": "Miami Heat",
    "Logo": "http://oit2.sps.nyu.edu/~tj986/Markericon/Miami%20Heat.gif",
    "Conference": "East",
    "Divisions": "SOUTHEAST",
    "Year": 1999,
    "Picture": "http://oit2.sps.nyu.edu/~tj986/Markericon/Image/MIA.jpg",
    "Capacity": "21,000"
  },
  {
    "StadiumName": "Fiserv Forum",
    "longitude": -87.9195802,
    "latitude": 43.0450841,
    "website": "https://www.nba.com/bucks/",
    "Team": "Milwaukee Bucks",
    "Logo": "http://oit2.sps.nyu.edu/~tj986/Markericon/Milwaukee%20Bucks.png",
    "Conference": "East",
    "Divisions": "CENTRAL",
    "Year": 2018,
    "Picture": "http://oit2.sps.nyu.edu/~tj986/Markericon/Image/MIL.jpg",
    "Capacity": "17,341"
  },
  {
    "StadiumName": "Target Center",
    "longitude": -93.278183,
    "latitude": 44.9795319,
    "website": "https://www.nba.com/timberwolves/",
    "Team": "Minnesota Timberwolves",
    "Logo": "http://oit2.sps.nyu.edu/~tj986/Markericon/Minnesota%20Timberwolves.png",
    "Conference": "West",
    "Divisions": "NORTHWEST",
    "Year": 1990,
    "Picture": "http://oit2.sps.nyu.edu/~tj986/Markericon/Image/MIN.jpg",
    "Capacity": "19,356"
  },
  {
    "StadiumName": "Smoothie King Center",
    "longitude": -90.0842508,
    "latitude": 29.9490397,
    "website": "https://www.nba.com/pelicans/",
    "Team": "New Orleans Pelicans",
    "Logo": "http://oit2.sps.nyu.edu/~tj986/Markericon/New%20Orleans%20Pelicans.png",
    "Conference": "West",
    "Divisions": "SOUTHWEST",
    "Year": 1999,
    "Picture": "http://oit2.sps.nyu.edu/~tj986/Markericon/Image/NO.jpg",
    "Capacity": "17,791"
  },
  {
    "StadiumName": "Madison Square Garden",
    "longitude": -73.9956327,
    "latitude": 40.7505085,
    "website": "https://www.nba.com/knicks/",
    "Team": "New York Knicks",
    "Logo": "http://oit2.sps.nyu.edu/~tj986/Markericon/New%20York%20Knicks.gif",
    "Conference": "East",
    "Divisions": "ATLANTIC",
    "Year": 1968,
    "Picture": "http://oit2.sps.nyu.edu/~tj986/Markericon/Image/NYK.jpg",
    "Capacity": "20,789"
  },
  {
    "StadiumName": "Chesapeake Energy Arena",
    "longitude": -97.5173078,
    "latitude": 35.463429,
    "website": "https://www.nba.com/thunder/",
    "Team": "Oklahoma City Thunder",
    "Logo": "http://oit2.sps.nyu.edu/~tj986/Markericon/Oklahoma%20City%20Thunder.png",
    "Conference": "West",
    "Divisions": "NORTHWEST",
    "Year": 2002,
    "Picture": "http://oit2.sps.nyu.edu/~tj986/Markericon/Image/OKC.jpg",
    "Capacity": "18,203"
  },
  {
    "StadiumName": "Amway Center",
    "longitude": -81.3860475,
    "latitude": 28.5392261,
    "website": "https://www.nba.com/magic/",
    "Team": "Orlando Magic",
    "Logo": "http://oit2.sps.nyu.edu/~tj986/Markericon/Orlando%20Magic.gif",
    "Conference": "East",
    "Divisions": "SOUTHEAST",
    "Year": 2010,
    "Picture": "http://oit2.sps.nyu.edu/~tj986/Markericon/Image/ORL.jpg",
    "Capacity": "20,000"
  },
  {
    "StadiumName": "Wells Fargo Center",
    "longitude": -75.1741735,
    "latitude": 39.9012056,
    "website": "https://www.nba.com/sixers/",
    "Team": "Philadelphia 76ers",
    "Logo": "http://oit2.sps.nyu.edu/~tj986/Markericon/Philadelphia%2076ers.png",
    "Conference": "East",
    "Divisions": "ATLANTIC",
    "Year": 1996,
    "Picture": "http://oit2.sps.nyu.edu/~tj986/Markericon/Image/PHI.jpg",
    "Capacity": "19,500"
  },
  {
    "StadiumName": "US Airways Center",
    "longitude": -112.0740501,
    "latitude": 33.4458798,
    "website": "https://www.nba.com/suns/",
    "Team": "Phoenix Suns",
    "Logo": "http://oit2.sps.nyu.edu/~tj986/Markericon/Phoenix%20Suns.png",
    "Conference": "West",
    "Divisions": "PACIFIC",
    "Year": 1992,
    "Picture": "http://oit2.sps.nyu.edu/~tj986/Markericon/Image/PHX.jpg",
    "Capacity": "18,422"
  },
  {
    "StadiumName": "Moda Center",
    "longitude": -122.6690363,
    "latitude": 45.5315688,
    "website": "https://www.nba.com/blazers/",
    "Team": "Portland Trail Blazers",
    "Logo": "http://oit2.sps.nyu.edu/~tj986/Markericon/Portland%20Trail%20Blazers.png",
    "Conference": "West",
    "Divisions": "NORTHWEST",
    "Year": 1995,
    "Picture": "http://oit2.sps.nyu.edu/~tj986/Markericon/Image/POR.jpg",
    "Capacity": "19,980"
  },
  {
    "StadiumName": "Sleep Train Arena",
    "longitude": -121.5203224,
    "latitude": 38.649043,
    "website": "https://www.nba.com/kings/",
    "Team": "Sacramento Kings",
    "Logo": "http://oit2.sps.nyu.edu/~tj986/Markericon/Sacramento%20Kings.png",
    "Conference": "West",
    "Divisions": "PACIFIC",
    "Year": 1988,
    "Picture": "http://oit2.sps.nyu.edu/~tj986/Markericon/Image/SAC.jpg",
    "Capacity": "17,317"
  },
  {
    "StadiumName": "AT&T Center",
    "longitude": -98.4396753,
    "latitude": 29.4271568,
    "website": "https://www.nba.com/spurs/",
    "Team": "San Antonio Spurs",
    "Logo": "http://oit2.sps.nyu.edu/~tj986/Markericon/San%20Antonio%20Spurs.png",
    "Conference": "West",
    "Divisions": "SOUTHWEST",
    "Year": 2002,
    "Picture": "http://oit2.sps.nyu.edu/~tj986/Markericon/Image/SAS.jpg",
    "Capacity": "18,581"
  },
  {
    "StadiumName": "Scotiabank Arena",
    "longitude": -79.3812929,
    "latitude": 43.64347,
    "website": "https://www.nba.com/raptors/",
    "Team": "Toronto Raptors",
    "Logo": "http://oit2.sps.nyu.edu/~tj986/Markericon/Toronto%20Raptors.png",
    "Conference": "East",
    "Divisions": "ATLANTIC",
    "Year": 1999,
    "Picture": "http://oit2.sps.nyu.edu/~tj986/Markericon/Image/TOR.jpeg",
    "Capacity": "19,800"
  },
  {
    "StadiumName": "Energy Solutions Arena",
    "longitude": -111.9032761,
    "latitude": 40.7682681,
    "website": "https://www.nba.com/jazz/",
    "Team": "Utah Jazz",
    "Logo": "http://oit2.sps.nyu.edu/~tj986/Markericon/Utah%20Jazz.png",
    "Conference": "West",
    "Divisions": "NORTHWEST",
    "Year": 1991,
    "Picture": "http://oit2.sps.nyu.edu/~tj986/Markericon/Image/Utah.jpg",
    "Capacity": "18,300"
  },
  {
    "StadiumName": "Capital One Arena",
    "longitude": -77.0229949,
    "latitude": 38.898065,
    "website": "https://www.nba.com/wizards/",
    "Team": "Washington Wizards",
    "Logo": "http://oit2.sps.nyu.edu/~tj986/Markericon/Washington%20Wizards.png",
    "Conference": "East",
    "Divisions": "SOUTHEAST",
    "Year": 1997,
    "Picture": "http://oit2.sps.nyu.edu/~tj986/Markericon/Image/WAS.jpg",
    "Capacity": "20,356"
  }
]
